---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-webhooks-mock
spec:
  selector:
    matchLabels:
      app: notifications-webhooks-mock
  replicas: 1
  template:
    metadata:
      labels:
        app: notifications-webhooks-mock
    spec:
      containers:
        - name: notifications-webhooks-mock
          image: quay.io/redhat-user-workloads/hcc-perfscale-tenant/iperf-notifications-mock:latest-main
          imagePullPolicy: Always
          env:
            - name: POSTGRESQL_HOST
              value: storage-postgresql-service
            - name: POSTGRESQL_PORT
              value: '5432'
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: storage-postgresql
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: storage-postgresql
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: storage-postgresql
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 250m
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-webhooks-mock-service
spec:
  selector:
    app: notifications-webhooks-mock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
...
